environment:
  global:
    npm_registry: https://registry.npmjs.com

  matrix:
    - nodejs_version: "4.3.2"
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i

test_script:
  - npm --version
  - npm run ci

build: off
